### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by michaelthorne** [laurenwaller/cssco#1]
When you have a moment, please can you remove all assets that aren't being used?
- [fonts](https://github.com/we-are-next/cssco/tree/master/src/assets/fonts)
- [images](https://github.com/we-are-next/cssco/tree/master/src/assets/images)
- [js](https://github.com/we-are-next/cssco/tree/master/src/assets/js)
- [sass](https://github.com/we-are-next/cssco/tree/master/src/assets/sass) (strip out utilities, print, etc. that isn't in use)

So `master` _only_ has the HTML + CSS (and JS if you are using any) for the CSSCO project i.e. all the stuff you need if you wanted to use it in a project of your own.

**Comment by laurenwaller** [comment]
@michaelthorne Yes indeed! Will do.

**Comment by michaelthorne** [comment]
You can also get rid of the polyfill scripts + browser upgrade prompt. :+1:
