### ISSUE TITLE
Create/add a `dist` folder

### ISSUE THREAD

**Issue by michaelthorne** [laurenwaller/cssco#3]
This would go in `master`, so that if you browse to https://github.com/we-are-next/cssco/tree/master/dist you could view the compiled/minified files (just CSS I assume?).

Essentially that would be what you would download/include in a project of your own to use the filters.

**Comment by laurenwaller** [comment]
Cool! I was thinking of including an `example.html` file showing how to use them, but not sure it's really necessary actually. It's not rocket science :) What do you think?

**Comment by michaelthorne** [comment]
It's up to you, I think your explanation in the `How to` section of the `README.md` is :100:

**Comment by laurenwaller** [comment]
I think I did this right? https://github.com/we-are-next/cssco/tree/gh-pages/dist

**Comment by michaelthorne** [comment]
@laurenwaller so this is what I'm thinking:

`master` is the branch where all the source code for **CSSCO** exists. But _only_ the CSS/Sass files, none of the HTML files/CSS for the [website](http://we-are-next.github.io/cssco/). So that means we strip out a bunch of stuff from `Gruntfile.js` i.e. `grunt connect`, `grunt watch`, etc.

So all you do if you check out `master` is run `grunt dist` to generate the compiled CSS from the `src` files. And you can lint them.

The `gh-pages` branch has all the HTML, CSS, etc. for the website _and_ the `cssco.css` file (generated from the `master` branch, it can be duplicated in there, that's fine).

Think of it this way, if someone wanted to use CSSCO, they'd download `cssco.css` and included it in _their_ HTML document. So I don't think we should be providing that, seeing as this is a CSS library.

If they wanted to modify/edit it, they could do that (edit the `cssco.scss` file, could even been plain old CSS - doesn't need to be Sass), then run `grunt dist` and include the CSS file in _their_ HTML source code.

That's why I think the `master` branch code should just be e.g. `src/sass/cssco.scss`

There's no real need for a `grunt connect` server for the website. We/you will be the only ones ever editing the public facing website. You can run that locally (directly in your browser), plus it's a GitHub Pages site so you could actually set it up to run with Jekyll (like wearenext.co.za) but that might be a bit overkill for such a small site at the moment.

Make sense?

**Comment by laurenwaller** [comment]
@michaelthorne Yeah that totally makes sense. No point in letting other people edit the actual website for the tool, only the tool itself, which is just css. I feel like it might help me if I could sit down with you when you have a moment just to clarify exactly how I go about doing everything above. Or maybe I'll try and if I get stuck I'll let you know. Probably better that way :)

**Comment by michaelthorne** [comment]
@laurenwaller cool. We can chat after the meeting, just to make sure we're on the same page. :+1:
